
import React, { useState, useEffect } from 'react';
import { WorkoutSession, AiInsight } from '../types';
import { getWorkoutInsights } from '../services/geminiService';

interface Props {
  sessions: WorkoutSession[];
}

const AiInsightsView: React.FC<Props> = ({ sessions }) => {
  const [insight, setInsight] = useState<AiInsight | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchInsights = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await getWorkoutInsights(sessions);
      if (result) {
        setInsight(result);
      } else {
        setError("Couldn't generate insights right now.");
      }
    } catch (e) {
      setError("An unexpected error occurred.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (sessions.length > 0 && !insight) {
      fetchInsights();
    }
  }, [sessions, insight]);

  if (sessions.length === 0) {
    return (
      <div className="p-8 text-center mt-20">
        <span className="material-icons text-6xl text-slate-300 mb-4">auto_awesome</span>
        <h2 className="text-xl font-bold text-slate-800">No Data for Analysis</h2>
        <p className="text-slate-500 mt-2">Log a few workouts first, and then our AI Coach can give you personalized tips!</p>
      </div>
    );
  }

  return (
    <div className="p-4 space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
          <span className="material-icons text-purple-600">psychology</span>
          AI Fitness Coach
        </h2>
        <button 
          onClick={fetchInsights}
          disabled={loading}
          className={`p-2 rounded-full transition-all ${loading ? 'animate-spin text-slate-400' : 'text-purple-600 hover:bg-purple-50'}`}
        >
          <span className="material-icons">refresh</span>
        </button>
      </div>

      {loading ? (
        <div className="space-y-4">
          <div className="h-32 bg-slate-200 animate-pulse rounded-2xl"></div>
          <div className="h-24 bg-slate-100 animate-pulse rounded-2xl"></div>
        </div>
      ) : insight ? (
        <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-700">
          {/* Main Insight Card */}
          <div className="bg-gradient-to-br from-purple-600 to-indigo-800 rounded-3xl p-8 text-white material-shadow-lg relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10">
              <span className="material-icons text-9xl">auto_awesome</span>
            </div>
            <h3 className="text-purple-100 font-bold uppercase tracking-widest text-xs mb-2">Coach's Insight</h3>
            <p className="text-2xl font-bold mb-4 leading-tight">{insight.title}</p>
            <p className="text-purple-50 leading-relaxed italic opacity-90 text-lg">
              "{insight.motivation}"
            </p>
          </div>

          {/* Suggestion Card */}
          <div className="bg-white rounded-2xl p-6 material-shadow border border-slate-100">
            <div className="flex items-center gap-3 mb-4">
              <div className="bg-amber-100 p-2 rounded-xl">
                <span className="material-icons text-amber-600">lightbulb</span>
              </div>
              <h4 className="font-bold text-slate-800">Action Plan</h4>
            </div>
            <p className="text-slate-600 leading-relaxed">
              {insight.suggestion}
            </p>
          </div>

          <div className="bg-purple-50 rounded-2xl p-6 flex items-start gap-4">
            <span className="material-icons text-purple-400">info</span>
            <p className="text-sm text-purple-700">
              These insights are generated by Gemini AI based on your recent training volume and frequency. Keep consistent!
            </p>
          </div>
        </div>
      ) : (
        <div className="text-center p-12 bg-white rounded-2xl material-shadow">
          <p className="text-slate-400">{error || "Something went wrong."}</p>
          <button 
            onClick={fetchInsights}
            className="mt-4 text-purple-600 font-bold hover:underline"
          >
            Try Again
          </button>
        </div>
      )}
    </div>
  );
};

export default AiInsightsView;
